select * from questions;

CREATE TABLE questions (
    question_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 질문 고유 ID (PK)
    parent_id NUMBER NOT NULL, -- 상위 엔티티 ID (모임ID 또는 관리자 영역 ID)
    member_id NUMBER NOT NULL, -- 질문 작성자 ID (members 테이블 참조)
    category VARCHAR2(10) DEFAULT 'MEETUP' CHECK (category IN ('MEETUP','ADMIN')), -- 질문 출처 구분 (모임/관리자)
    title VARCHAR2(200) NOT NULL, -- 질문 제목
    content CLOB NOT NULL, -- 질문 내용
    status VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING','ANSWERED')), -- 질문 상태 (처리대기/처리완료)
    is_public CHAR(1) DEFAULT 'Y' CHECK (is_public IN ('Y','N')), -- 공개 여부 (Y=공개, N=비공개)
    delete_yn CHAR(1) DEFAULT 'N' CHECK (delete_yn IN ('Y','N')), -- 삭제 여부 (N=정상, Y=삭제)
    analysis_status VARCHAR2(20) DEFAULT 'NORMAL' CHECK (analysis_status IN ('NORMAL','PENDING_REVIEW','REJECTED')), -- AI 검토 상태
    aggression_score NUMBER(5,2), -- AI 공격성 점수
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 생성일시
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 수정일시
    CONSTRAINT fk_question_member FOREIGN KEY (member_id) REFERENCES members(member_id) -- 작성자 FK
);
CREATE OR REPLACE TRIGGER trg_questions_updated
BEFORE UPDATE ON questions
FOR EACH ROW BEGIN :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/
CREATE TABLE answers (
    answer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 답변 고유 ID (PK)
    question_id NUMBER NOT NULL UNIQUE, -- 연결된 질문 ID (질문당 답변 1개만 허용)
    member_id NUMBER NOT NULL, -- 답변 작성자 ID (게시자/관리자)
    content CLOB NOT NULL, -- 답변 내용
    is_public CHAR(1) DEFAULT 'Y' CHECK (is_public IN ('Y','N')), -- 공개 여부 (Y=공개, N=비공개)
    delete_yn CHAR(1) DEFAULT 'N' CHECK (delete_yn IN ('Y','N')), -- 삭제 여부 (N=정상, Y=삭제)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 생성일시
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 수정일시
    CONSTRAINT fk_answer_question FOREIGN KEY (question_id) REFERENCES questions(question_id), -- 질문 FK
    CONSTRAINT fk_answer_member FOREIGN KEY (member_id) REFERENCES members(member_id) -- 작성자 FK
);
CREATE OR REPLACE TRIGGER trg_answers_updated
BEFORE UPDATE ON answers
FOR EACH ROW BEGIN :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/
CREATE TABLE notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 알림 PK
    question_id NUMBER NOT NULL, -- 알림 발생 대상 문의
    member_id NUMBER NOT NULL, -- 알림 수신 회원
    type VARCHAR2(30) NOT NULL CHECK (type IN ('QUESTION_CREATED','ANSWER_CREATED','QUESTION_REVIEW','QUESTION_REJECTED')), -- 알림 유형
    message VARCHAR2(255) NOT NULL, -- 알림 메시지
    is_read CHAR(1) DEFAULT 'N' CHECK (is_read IN ('Y','N')), -- 읽음 여부
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 생성일
    CONSTRAINT fk_notification_question FOREIGN KEY (question_id) REFERENCES questions(question_id), -- 문의 FK
    CONSTRAINT fk_notification_member FOREIGN KEY (member_id) REFERENCES members(member_id) -- 회원 FK
);